import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/header";
import { Hero } from "@/components/Hero/hero";
import { About } from "@/components/About/about";
import { Know } from "@/components/Know/know";
import { Footer } from "@/components/Footer/footer";

const nunito = Nunito({
  weight: ['400', '600', '700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={nunito.className}>
        <Header/>
        <Hero />
        <Know />
        <About />
        <Footer />
        {children}
      </body>
    </html>
  );
}
